[package]
name = "really-bad-idea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
politeness-macro = {path = "../politeness-macro", version = "^0.1.0"}